"""
SciCap Dataset Loader
Scientific figure captions from ArXiv papers.
400K+ figures across 8 scientific categories: CS, Economics, EE, Math, Physics, Bio, Finance, Stats.
Includes both original and high-quality MLBCAP version (2025).
"""

import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))

from datasets import load_dataset
from tqdm import tqdm
from PIL import Image
import io


def load_scicap(num_pairs=400_000):
    """
    Load SciCap (CrowdAILab/scicap)
    400K scientific figures with captions from ArXiv papers.

    Args:
        num_pairs: Target number of image-caption pairs to load

    Returns:
        List of dicts with 'image' and 'caption' keys
    """
    print("\n" + "="*60)
    print("Loading SciCap (CrowdAILab/scicap)...")
    print(f"Target pairs: {num_pairs:,}")
    print("="*60)

    try:
        ds = load_dataset(
            "CrowdAILab/scicap",
            split="train",
            streaming=True
        )
        ds = ds.shuffle(seed=42).take(num_pairs)

        formatted = []
        for example in tqdm(ds, desc="Processing SciCap", total=num_pairs):
            image = example.get("image", None)
            caption = example.get("caption", "").strip()

            if image is not None and caption:
                formatted.append({
                    "image": image,
                    "caption": caption
                })

        print(f"✓ Loaded {len(formatted):,} image-caption pairs from SciCap")
        return formatted

    except Exception as e:
        print(f"✗ Error loading SciCap: {e}")
        return []


def load_scicap_chunked(num_pairs=400_000, chunk_size=5000):
    """
    Load SciCap in chunks to avoid RAM overflow.
    Yields batches of image-caption pairs instead of loading everything at once.
    NO SHUFFLE - maintains deterministic order for checkpointing.

    Args:
        num_pairs: Target number of image-caption pairs to load
        chunk_size: Number of pairs per chunk

    Yields:
        List of dicts with 'image' and 'caption' keys
    """
    print("\n" + "="*60)
    print("Loading SciCap (CrowdAILab/scicap) in chunks...")
    print(f"Target pairs: {num_pairs:,}")
    print(f"Chunk size: {chunk_size:,} pairs")
    print("="*60)

    try:
        ds = load_dataset(
            "CrowdAILab/scicap",
            split="train",
            streaming=True
        )
        ds = ds.take(num_pairs)

        chunk = []
        total_processed = 0

        for example in tqdm(ds, desc="Processing SciCap", total=num_pairs):
            image = example.get("image", None)
            caption = example.get("caption", "").strip()

            if image is not None and caption:
                chunk.append({
                    "image": image,
                    "caption": caption
                })

            if len(chunk) >= chunk_size:
                yield chunk
                total_processed += len(chunk)
                chunk = []

        if chunk:
            yield chunk
            total_processed += len(chunk)

        print(f"✓ Processed {total_processed:,} pairs from SciCap")

    except Exception as e:
        print(f"✗ Error loading SciCap: {e}")
        yield []


def load_scicap_mlbcap(num_pairs=400_000):
    """
    Load SciCap-MLBCAP (TEAMREBOOTT-AI/SciCap-MLBCAP)
    High-quality synthetic captions generated by multi-LLM approach (2025).

    Args:
        num_pairs: Target number of image-caption pairs to load

    Returns:
        List of dicts with 'image' and 'caption' keys
    """
    print("\n" + "="*60)
    print("Loading SciCap-MLBCAP (TEAMREBOOTT-AI/SciCap-MLBCAP)...")
    print(f"Target pairs: {num_pairs:,}")
    print("="*60)

    try:
        ds = load_dataset(
            "TEAMREBOOTT-AI/SciCap-MLBCAP",
            split="train",
            streaming=True
        )
        ds = ds.shuffle(seed=42).take(num_pairs)

        formatted = []
        for example in tqdm(ds, desc="Processing SciCap-MLBCAP", total=num_pairs):
            image = example.get("image", None)
            caption = example.get("caption", "").strip()

            if image is not None and caption:
                formatted.append({
                    "image": image,
                    "caption": caption
                })

        print(f"✓ Loaded {len(formatted):,} image-caption pairs from SciCap-MLBCAP")
        return formatted

    except Exception as e:
        print(f"✗ Error loading SciCap-MLBCAP: {e}")
        return []


def load_scicap_mlbcap_chunked(num_pairs=400_000, chunk_size=5000):
    """
    Load SciCap-MLBCAP in chunks.

    Args:
        num_pairs: Target number of image-caption pairs to load
        chunk_size: Number of pairs per chunk

    Yields:
        List of dicts with 'image' and 'caption' keys
    """
    print("\n" + "="*60)
    print("Loading SciCap-MLBCAP (TEAMREBOOTT-AI/SciCap-MLBCAP) in chunks...")
    print(f"Target pairs: {num_pairs:,}")
    print(f"Chunk size: {chunk_size:,} pairs")
    print("="*60)

    try:
        ds = load_dataset(
            "TEAMREBOOTT-AI/SciCap-MLBCAP",
            split="train",
            streaming=True
        )
        ds = ds.take(num_pairs)

        chunk = []
        total_processed = 0

        for example in tqdm(ds, desc="Processing SciCap-MLBCAP", total=num_pairs):
            image = example.get("image", None)
            caption = example.get("caption", "").strip()

            if image is not None and caption:
                chunk.append({
                    "image": image,
                    "caption": caption
                })

            if len(chunk) >= chunk_size:
                yield chunk
                total_processed += len(chunk)
                chunk = []

        if chunk:
            yield chunk
            total_processed += len(chunk)

        print(f"✓ Processed {total_processed:,} pairs from SciCap-MLBCAP")

    except Exception as e:
        print(f"✗ Error loading SciCap-MLBCAP: {e}")
        yield []


if __name__ == "__main__":
    data = load_scicap(num_pairs=100)
    print(f"\nLoaded {len(data)} pairs")
    print(f"Sample caption: {data[0]['caption'][:200]}...")
